- name: Disable IPv6
  hosts: localhost
  become: yes
  tasks:
    - name: Disable IPv6 in sysctl
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        reload: yes
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
