version: '3.8'

services:
  fastapi:
    image: python:3.9
    volumes:
      - ./fastapi:/app
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    environment:
      - PYTHON_VERSION=3.9

  redis:
    image: redis:latest
    ports:
      - "6379:6379"